apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-project5
  labels:
    app: capstone-project5

spec:
  selector:
    matchLabels:
      app: capstone-project5
  
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: capstone-project5
    
    spec:
      containers:
      - name: capstone-project5
        image: gchawla21/capstone-project5
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
