apiVersion: v1
kind: Service
metadata:
  name: capstone-project5
  labels:
    app: capstone-project5
spec:
  type: LoadBalancer
  selector:
    app: capstone-project5
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 80
